CREATE TABLE COMTCCMMNCLCODE
(
  CL_CODE               CHAR(3) NOT NULL,
  CL_CODE_NM            VARCHAR(60) NULL,
  CL_CODE_DC            VARCHAR(200) NULL,
  USE_AT                CHAR(1) NULL,
  FRST_REGIST_PNTTM     DATETIME NULL,
  FRST_REGISTER_ID      VARCHAR(20) NULL,
  LAST_UPDT_PNTTM       DATETIME NULL,
  LAST_UPDUSR_ID        VARCHAR(20) NULL,
   PRIMARY KEY (CL_CODE)
)
;



CREATE UNIQUE INDEX COMTCCMMNCLCODE_PK ON COMTCCMMNCLCODE
(
  CL_CODE
)
;



CREATE TABLE COMTCCMMNCODE
(
  CODE_ID               VARCHAR(6) NOT NULL,
  CODE_ID_NM            VARCHAR(60) NULL,
  CODE_ID_DC            VARCHAR(200) NULL,
  USE_AT                CHAR(1) NULL,
  CL_CODE               CHAR(3) NULL,
  FRST_REGIST_PNTTM     DATETIME NULL,
  FRST_REGISTER_ID      VARCHAR(20) NULL,
  LAST_UPDT_PNTTM       DATETIME NULL,
  LAST_UPDUSR_ID        VARCHAR(20) NULL,
   PRIMARY KEY (CODE_ID),
  FOREIGN KEY COMTCCMMNCODE_FK1 (CL_CODE) REFERENCES COMTCCMMNCLCODE(CL_CODE)
)
;



CREATE UNIQUE INDEX COMTCCMMNCODE_PK ON COMTCCMMNCODE
(
  CODE_ID
)
;



CREATE INDEX COMTCCMMNCODE_i01 ON COMTCCMMNCODE
(
  CL_CODE
)
;



CREATE TABLE COMTCCMMNDETAILCODE
(
  CODE_ID               VARCHAR(6) NOT NULL,
  CODE                  VARCHAR(15) NOT NULL,
  CODE_NM               VARCHAR(60) NULL,
  CODE_DC               VARCHAR(200) NULL,
  USE_AT                CHAR(1) NULL,
  FRST_REGIST_PNTTM     DATETIME NULL,
  FRST_REGISTER_ID      VARCHAR(20) NULL,
  LAST_UPDT_PNTTM       DATETIME NULL,
  LAST_UPDUSR_ID        VARCHAR(20) NULL,
   PRIMARY KEY (CODE_ID,CODE),
  FOREIGN KEY COMTCCMMNDETAILCODE_FK1 (CODE_ID) REFERENCES COMTCCMMNCODE(CODE_ID)
)
;



CREATE UNIQUE INDEX COMTCCMMNDETAILCODE_PK ON COMTCCMMNDETAILCODE
(
  CODE_ID,
  CODE
)
;



CREATE INDEX COMTCCMMNDETAILCODE_i01 ON COMTCCMMNDETAILCODE
(
  CODE_ID
)
;